export const Auth = {
  USERNAME_CHANGED: 'auth/USERNAME_CHANGED',
  USERNAME_INCORRECT: 'auth/USERNAME_INCORRECT',
  PASSWORD_CHANGED: 'auth/PASSWORD_CHANGED',
  PASSWORD_INCORRECT: 'auth/PASSWORD_INCORRECT',
  PHONENUMBER_CHANGED: 'auth/PHONENUMBER_CHANGED',
  PHONENUMBER_INCORRECT: 'auth/PHONENUMBER_INCORRECT',

  
  DESCRIPTION_CHANGED: 'auth/DESCRIPTION_CHANGED',
  EMAIL_CHANGED: 'auth/EMAIL_CHANGED',
  EMAIL_INCORRECT: 'auth/EMAIL_INCORRECT',
  OTP_CHANGED: 'auth/OTP_CHANGED',
  OTP_INCORRECT: 'authOTP_INCORRECT/',
  LOGIN_USER_ATTEMPT: 'auth/LOGIN_USER_ATTEMPT',
  LOGIN_USER_SUCCESS: 'auth/LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'auth/LOGIN_USER_FAIL',

  SIGNUP_USER_ATTEMPT: 'auth/SIGNUP_USER_ATTEMPT',
  SIGNUP_USER_SUCCESS: 'auth/SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAIL: 'auth/SIGNUP_USER_FAIL',

  SIGNUP2_USER_ATTEMPT: 'auth/SIGNUP2_USER_ATTEMPT',
  SIGNUP2_USER_SUCCESS: 'auth/SIGNUP2_USER_SUCCESS',
  SIGNUP2_USER_FAIL: 'auth/SIGNUP2_USER_FAIL',


  CREATE_GUEST_SESSION_ATTEMPT: 'auth/CREATE_GUEST_SESSION_ATTEMPT',
  CREATE_GUEST_SESSION_SUCCESS: 'auth/CREATE_GUEST_SESSION_SUCCESS',
  CREATE_GUEST_SESSION_FAIL: 'auth/CREATE_GUEST_SESSION_FAIL',

  CLEAR_LOGIN_FIELDS: 'auth/CLEAR_LOGIN_FIELDS',
  USER_LOADED: 'auth/USER_LOADED',
  LOG_OUT: 'auth/LOG_OUT',
};

export const Skill = {
  GET_SKILLS: 'skill_GET_SKILLS',
  POST_SKILL: 'skills_POST_SKILL',
  POST_SKILL_SUCCESS: 'skills_POST_SKILL_SUCCESS',
  POST_SKILL_FAILED: 'skills_POST_SKILL_FAILED',
};
